baseURL: "https://ankithans.github.io/blog"
title: Ankit Hans
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: UA-123-45
disqusShortname: ankithans

minify:
  disableXML: true
  # minifyOutput: true

# params:
#   env: production # to enable google analytics, opengraph, twitter-cards and schema.
# title: Ankit Hans
# description: "Ankit Hans's Blog"
#   keywords: [Ankit Hans, Blog, Portfolio, PaperMod]
#   author: Me
#   # author: ["Me", "You"] # multiple authors
#   images: ["<link or path of image for opengraph, twitter-cards>"]
#   DateFormat: "January 2, 2006"
#   defaultTheme: auto # dark, light
#   disableThemeToggle: false

#   ShowReadingTime: true
#   ShowShareButtons: true
#   ShowPostNavLinks: true
#   ShowBreadCrumbs: true
#   ShowCodeCopyButtons: false
#   disableSpecial1stPost: false
#   disableScrollToTop: false
#   comments: false
#   hidemeta: false
#   hideSummary: false
#   showtoc: false
#   tocopen: false

#   assets:
#     # disableHLJS: true # to disable highlight.js
#     # disableFingerprinting: true
#     favicon: "<link / abs url>"
#     favicon16x16: "<link / abs url>"
#     favicon32x32: "<link / abs url>"
#     apple_touch_icon: "<link / abs url>"
#     safari_pinned_tab: "<link / abs url>"

#   label:
#     text: "Home"
#     icon: /apple-touch-icon.png
#     iconHeight: 35

#   # profile-mode
#   profileMode:
#     enabled: false # needs to be explicitly set
#     title: ExampleSite
#     subtitle: "This is subtitle"
#     imageUrl: "<img location>"
#     imageWidth: 120
#     imageHeight: 120
#     imageTitle: my image
#     buttons:
#       - name: Posts
#         url: posts
#       - name: Tags
#         url: tags

#   # home-info mode
#   homeInfoParams:
#     Title: "Hi there \U0001F44B"
#     Content: Welcome to my blog

#   socialIcons:
#     - name: twitter
#       url: "https://twitter.com/"
#     - name: stackoverflow
#       url: "https://stackoverflow.com"
#     - name: github
#       url: "https://github.com/"

#   analytics:
#     google:
#       SiteVerificationTag: "XYZabc"
#     bing:
#       SiteVerificationTag: "XYZabc"
#     yandex:
#       SiteVerificationTag: "XYZabc"

#   cover:
#     hidden: true # hide everywhere but not in structured data
#     hiddenInList: true # hide on list pages and home
#     hiddenInSingle: true # hide on single page

#   editPost:
#     URL: "https://github.com/<path_to_repo>/content"
#     Text: "Suggest Changes" # edit text
#     appendFilePath: true # to append file path to Edit link

#   # for search
#   # https://fusejs.io/api/options.html
#   fuseOpts:
#     isCaseSensitive: false
#     shouldSort: true
#     location: 0
#     distance: 1000
#     threshold: 0.4
#     minMatchCharLength: 0
#     keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - name: Archive
      url: archives/
      weight: 5
    # - name: Search
    #   url: /search/
    #   weight: 10
    - name: Tags
      url: tags/
      weight: 10
    - name: Categories
      url: categories/
      weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ankit Hans
  description: "Ankit Hans's Blog"
  author: Me
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  comments: true
  images: ["papermod-cover.png"]

  profileMode:
    enabled: false
    title: Ankit Hans
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Ankit Hans"
    Content: >
      Hi, I am a **Software Developer**

      - I am a Full Stack Developer, Open Source enthusiast and I love building great and cool stuffs for the community.

      - I am deeply passionate about sotware development and innovations.

  socialIcons:
    - name: github
      url: "https://github.com/ankithans"
    - name: linkedin
      url: "https://www.linkedin.com/in/ankithans/"
    - name: twitter
      url: "https://twitter.com/AnkitHans15"
    - name: "instagram"
      url: "https://www.instagram.com/thisisankithans/"
    - name: "email"
      url: "mailto:ankithans1947@gmail.com"

  editPost:
    URL: "https://github.com/ankithans/blog/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

taxonomies:
  series: series
  categories: categories
  tags: tags
